import{a as v,S as N,i as n}from"./assets/vendor-cf86d4d0.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))u(s);new MutationObserver(s=>{for(const a of s)if(a.type==="childList")for(const m of a.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&u(m)}).observe(document,{childList:!0,subtree:!0});function t(s){const a={};return s.integrity&&(a.integrity=s.integrity),s.referrerPolicy&&(a.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?a.credentials="include":s.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(s){if(s.ep)return;s.ep=!0;const a=t(s);fetch(s.href,a)}})();async function h(e){e=encodeURIComponent(e);const l="43812511-1ad98af5969ab2e5e6977c36e",t=new URLSearchParams({per_page:d,page:i,key:l,image_type:"photo",orientation:"horizontal",safesearch:"true"});return(await v.get(`https://pixabay.com/api/?${t}&q=${e}`)).data}const L=document.querySelector(".gallery");let g;function y(e){if(!Array.isArray(e)){console.error("Expected an array, but received:",e);return}const l=e.map(t=>`<li class="gallery-item">
  <a class="gallery-link" href="${t.largeImageURL}">
    <img
            src="${t.webformatURL}"
            alt="${t.tags}"
            width="360"
            height="200"
            class="gallery-img"
        />
        <ul class="gal-list">
        <li class="gal-link"><span class="gal-span">Likes</span> ${t.likes}</li>
        <li class="gal-link"><span class="gal-span">Views</span> ${t.views}</li>
        <li class="gal-link"><span class="gal-span">Comments</span> ${t.comments}</li>
        <li class="gal-link"><span class="gal-span">Downloads</span> ${t.downloads}</li>
     </ul>
  </a>
</li>`).join("");L.insertAdjacentHTML("beforeend",l),g?g.refresh():g=new N(".gallery a",{captionsData:"alt",captionDelay:250})}const f=document.querySelector("ul.gallery");let c="";const p=document.getElementById("search-input");let i=1,d=15;const o=document.getElementById("load-button"),r=document.getElementById("loader");p.addEventListener("input",e=>{c=p.value.trim(),f.innerHTML="",o.className="visually-hidden",r.className="visually-hidden"});const b=document.getElementById("search-button");b.addEventListener("click",async()=>{f.innerHTML="",r.className="loader",i=1,d=15;try{if(c){o.className="";const e=await h(c,i,d);e.hits.length===0?(n.error({title:"No results",message:"No images found for your search query.",position:"topRight"}),o.className="visually-hidden"):y(e.hits),r.className="loader visually-hidden",i+=1}else r.className="loader visually-hidden",n.error({title:"Error",message:"Please enter a search query.",position:"topRight"})}catch(e){r.className="loader visually-hidden",o.className="visually-hidden",console.log(e),n.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}});o.addEventListener("click",async()=>{r.className="loader";try{if(c){const e=await h(c,i,d),l=e.totalHits;if(document.querySelectorAll(".gallery-item").length>=l)return o.className="visually-hidden",r.className="visually-hidden",n.error({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});e.hits.length===0?(o.className="visually-hidden",r.className="loader visually-hidden"):(y(e.hits),r.className="loader visually-hidden",i+=1)}else r.className="loader visually-hidden"}catch(e){r.className="loader visually-hidden",console.log(e),n.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}});
//# sourceMappingURL=commonHelpers.js.map
